export const OPEN_COLLECTION = 'OPEN_COLLECTION';
export const CREATE_COLLECTION = 'CREATE_COLLECTION';
export const DELETE_COLLECTION = 'DELETE_COLLECTION';
export const EDIT_COLLECTION = 'EDIT_COLLECTION';

export const CREATE_TASK = 'CREATE_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const EDIT_TASK = 'EDIT_TASK';
export const ARCHIVE_TASK = 'ARCHIVE_TASK';

export const TOGGLE_THEME = 'TOGGLE_THEME';
export const SETUP_PROGRESS = 'SETUP_PROGRESS';


